services:
    postgresql:
        container_name: database
        image: postgres:alpine
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_UESR="postgres"
            - POSTGRES_PASSWORD="pswd"
            - POSTGRES_DB="spring_shop"            
    #redis:
    #    container_name: redis_cache
    #    image: redis:alpine
    #    ports:
    #        - "6379:6379"

    shop:
        container_name: app
        build: .
        ports:
            - "8080:8080"
        network_mode: host
        
