services:

    postgresql:
        container_name: user_credentials
        image: postgres:alpine
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_UESR="postgres"
            - POSTGRES_PASSWORD="pswd"
            - POSTGRES_DB="spring_db"
        healthcheck:
            - test: ["CMD-SHELL", "pg_isready -U postgres -d spring_db"]
            - timeout: 15s
            - retries: 5
            
    mongodb:
        container_name: buckets_products
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            - MY_CONFIG_MONGODB_ADMINUSERNAME="mongo"
            - MY_CONFIG_MONGODB_ADMIN_PASSWORD="pswd"
