services:
    postgresql:
        container_name: database
        image: postgres:alpine
        ports: 
            - 5432:5432
        environment:
            - POSTGRES_UESR="postgres"
            - POSTGRES_PASSWORD="pswd"
            - POSTGRES_DB="spring_shop"            
    mongodb:
        container_name: buckets_products
        image: mongo:4
        ports:
            - 8081:8081
        environment:
            - MY_CONFIG_MONGODB_ADMINUSERNAME="mongo"
            - MY_CONFIG_MONGODB_ADMIN_PASSWORD="pswd"
