
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_registr
    username: postgres
    password: pswd
  flyway:
    baseline-on-migrate: true
