spring:
  #datasource2:
  #  url: jdbc:mongodb://localhost:8081/spring_shop
  #  username: mongo
  #  password: pswd
  mvc:
    view:
      suffix: .html
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  jpa:
    hibernate:
      ddl-auto: update
