CREATE TABLE IF NOT EXISTS users_cred(
    id  BIGINT NOT NULL PRIMARY KEY,
    password VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS users(
    id  BIGINT NOT NULL PRIMARY KEY,
    first_name VARCHAR(20) NOT NULL,
    second_name VARCHAR(20) NOT NULL,
    email VARCHAR(20) NOT NULL,
    role VARCHAR(255),
    UNIQUE (email)
);

CREATE SEQUENCE IF NOT EXISTS user_seq
AS BIGINT
START WITH 100;

CREATE TABLE IF NOT EXISTS orders(
    order_id BIGINT NOT NULL PRIMARY KEY,
    created date NOT NULL,
    updated date NOT NULL,
    sum INT,
    address VARCHAR(40) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS order_seq
    AS BIGINT
    START WITH 100;

CREATE TABLE IF NOT EXISTS products(
    product_id  BIGINT NOT NULL PRIMARY KEY,
    title VARCHAR(20) NOT NULL,
    description VARCHAR(200) NOT NULL,
    price FLOAT
);

CREATE SEQUENCE IF NOT EXISTS product_seq
    AS BIGINT
    START WITH 100;

CREATE TABLE IF NOT EXISTS categories(
    category_id BIGINT NOT NULL PRIMARY KEY ,
    category_name VARCHAR(20)
);

CREATE SEQUENCE IF NOT EXISTS category_seq
    AS BIGINT
    START WITH 100;

CREATE TABLE IF NOT EXISTS buckets(
    user_id  BIGINT NOT NULL,
    products INTEGER[][]
);

CREATE SEQUENCE IF NOT EXISTS bucket_seq
    AS BIGINT
    START WITH 100;
