create sequence bucket_seq start 1 increment 1;
create sequence category_seq start 1 increment 1;
create sequence order_details_seq start 1 increment 1;
create sequence order_seq start 1 increment 1;
create sequence product_seq start 1 increment 1;
create sequence user_seq start 1 increment 1;
create table bucket_products (bucket_id int8 not null, product_id int8 not null);
create table buckets (id int8 not null, user_id int8, primary key (id));
create table categories (id int8 not null, seq_name varchar(255), category_name varchar(255), primary key (id));
create table order_details (id int8 not null, seq_name varchar(255), amount int4 not null, price int4 not null, order_id int8, product_id int8, primary key (id));
create table orders (id int8 not null, seq_name varchar(255), address varchar(255), created timestamp, status varchar(255), sum int4 not null, updated timestamp, user_id int8, primary key (id));
create table orders_details (order_id int8 not null, details_id int8 not null);
create table product_categories (product_id int8 not null, category_id int8 not null);
create table products (id int8 not null, description varchar(255), price float4 not null, title varchar(255), primary key (id));
create table users (id int8 not null, app_user_role varchar(255), archive boolean not null, email varchar(255), enabled boolean, first_name varchar(255), last_name varchar(255), locked boolean, password varchar(255), bucket_id int8, primary key (id));
alter table if exists orders_details add constraint order_details_un_details unique (details_id);
alter table if exists bucket_products add constraint bucket_products_fk_products foreign key (product_id) references products;
alter table if exists bucket_products add constraint bucket_products_fk_buckets foreign key (bucket_id) references buckets;
alter table if exists buckets add constraint buckets_fk_users foreign key (user_id) references users;
alter table if exists order_details add constraint orders_details_orders foreign key (order_id) references orders;
alter table if exists order_details add constraint orders_details_fk_products foreign key (product_id) references products;
alter table if exists orders add constraint orders_fk_users foreign key (user_id) references users;
alter table if exists orders_details add constraint orders_details_fk_order_det foreign key (details_id) references order_details;
alter table if exists orders_details add constraint orders_details_fk_orders foreign key (order_id) references orders;
alter table if exists product_categories add constraint product_categories_fk_cat foreign key (category_id) references categories;
alter table if exists product_categories add constraint product_categories_fk_products foreign key (product_id) references products;
alter table if exists users add constraint users_fk_buckets foreign key (bucket_id) references buckets;